version: '3'

services:
  web:
    build:
      #context is telling the which directory to search the files in
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - C:/Users/admin/docker_ex/frontend:/app
    stdin_open: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]
